default: &default
 adapter: postgresql
 encoding: unicode

development:
 <<: *default
 database: wenote_development

test:
 <<: *default
 database: wenote_test

production:
 <<: *default
 database: wenote_production
 username: wenote
 password: <%= ENV['WENOTE_DATABASE_PASSWORD'] %>